CREATE TABLE ADDRESSBOOK_CONTACTS (
  AC_CONTACT_ID   INTEGER,
  AC_FIRST_NAME   VARCHAR2(25),
  AC_LAST_NAME    VARCHAR2(25),
  AC_COMPANY      VARCHAR2(25),
  AC_CONTENT_TYPE VARCHAR2(25),
  AC_PHOTO        BLOB,
  PRIMARY KEY (AC_CONTACT_ID)
);

CREATE TABLE ADDRESSBOOK_PHONENUMBERS (
  AP_CONTACT_ID INTEGER,
  AP_NUMBER     VARCHAR2(25),
  FOREIGN KEY (AP_CONTACT_ID) REFERENCES ADDRESSBOOK_CONTACTS (AC_CONTACT_ID)
);

CREATE SEQUENCE contacts_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 10;

CREATE OR REPLACE PROCEDURE GET_ALL_CONTACT_DATA
  (ID_CONTACT      IN  INTEGER, v_first_name OUT VARCHAR2,
   v_last_name     OUT VARCHAR2, v_company OUT VARCHAR2,
   v_photo         OUT BLOB, v_content_type OUT VARCHAR2,
   v_phone_numbers OUT SYS_REFCURSOR)
IS

  CURSOR ALL_DATA(ID_CONTACT INTEGER) IS
    SELECT
      ADDRESSBOOK_CONTACTS.AC_FIRST_NAME,
      ADDRESSBOOK_CONTACTS.AC_LAST_NAME,
      ADDRESSBOOK_CONTACTS.AC_COMPANY,
      ADDRESSBOOK_CONTACTS.AC_CONTENT_TYPE,
      ADDRESSBOOK_CONTACTS.AC_PHOTO
    FROM ADDRESSBOOK_CONTACTS
    WHERE AC_CONTACT_ID = ID_CONTACT;

  BEGIN
    OPEN all_data(id_contact);
    LOOP
      FETCH all_data INTO v_first_name, v_last_name, v_company, v_photo, v_content_type;
      EXIT WHEN all_data%NOTFOUND;
    END LOOP;
    CLOSE all_data;
    OPEN v_phone_numbers FOR
    SELECT AP_NUMBER
    FROM ADDRESSBOOK_PHONENUMBERS
    WHERE AP_CONTACT_ID = ID_CONTACT;

  END;

INSERT INTO ADDRESSBOOK_CONTACTS (AC_CONTACT_ID, AC_FIRST_NAME, AC_LAST_NAME, AC_COMPANY)
VALUES (CONTACTS_SEQUENCE.NEXTVAL, 'Alex', 'Birsan', 'SRL');
INSERT INTO ADDRESSBOOK_CONTACTS (AC_CONTACT_ID, AC_FIRST_NAME, AC_LAST_NAME, AC_COMPANY)
VALUES (CONTACTS_SEQUENCE.NEXTVAL, 'Ion', 'Popescu', 'OPTY');
INSERT INTO ADDRESSBOOK_CONTACTS (AC_CONTACT_ID, AC_FIRST_NAME, AC_LAST_NAME, AC_COMPANY)
VALUES (CONTACTS_SEQUENCE.NEXTVAL, 'Alina', 'Dumitrescu', 'SRL');

INSERT INTO ADDRESSBOOK_PHONENUMBERS VALUES (1, '075-2028861');
INSERT INTO ADDRESSBOOK_PHONENUMBERS VALUES (1, '074-2025861');
INSERT INTO ADDRESSBOOK_PHONENUMBERS VALUES (3, '073-0028861');

